# Generated by Django 6.0.3 on 2026-06-10 00:07

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, validators=[api.models.validate_email])),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.UUIDField(db_column='bike_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(80)])),
                ('size', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1)),
            ],
            options={
                'db_table': 'bikes',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.UUIDField(db_column='caregiver_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, validators=[api.models.validate_email])),
                ('phone', models.TextField(blank=True, null=True, validators=[api.models.validate_phone])),
                ('isemergencycontact', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caregivers',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.UUIDField(db_column='leader_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, validators=[api.models.validate_email])),
            ],
            options={
                'db_table': 'leaders',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessionnumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('starttime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skillname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('formlevel', models.IntegerField(choices=[(1, 'Level One'), (2, 'Level Two'), (3, 'Level Three'), (4, 'Level Four')], default=1)),
                ('category', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[api.models.validate_email])),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('leader', 'Leader'), ('caregiver', 'Caregiver'), ('anonymous', 'Anonymous/Sub User')], default='anonymous', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('caregiver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.caregiver')),
                ('leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.leader')),
            ],
            options={
                'db_table': 'accounts',
            },
            managers=[
                ('objects', api.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(db_column='rider_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('lastname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('isquickstart', models.BooleanField(blank=True, null=True)),
                ('caregivers', models.ManyToManyField(related_name='riders', to='api.caregiver')),
                ('leader', models.ForeignKey(blank=True, db_column='leader_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='api.leader')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.session')),
            ],
            options={
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='BikeSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Day One'), (2, 'Day Two'), (3, 'Day Three'), (4, 'Day Four'), (5, 'Day Five')], default=1)),
                ('seat_height', models.FloatField()),
                ('left_piston', models.FloatField()),
                ('right_piston', models.FloatField()),
                ('bike', models.ForeignKey(db_column='bike_id', on_delete=django.db.models.deletion.CASCADE, to='api.bike')),
                ('rider', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
            options={
                'db_table': 'bike_specs',
                'unique_together': {('bike', 'rider', 'day')},
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='riders',
            field=models.ManyToManyField(through='api.BikeSpecs', to='api.rider'),
        ),
        migrations.CreateModel(
            name='FinalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_forms', to='api.leader')),
                ('rider', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_forms', to='api.rider')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_forms', to='api.session')),
            ],
            options={
                'db_table': 'final_forms',
            },
        ),
        migrations.CreateModel(
            name='DailyForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_forms', to='api.leader')),
                ('rider', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_forms', to='api.rider')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.session')),
            ],
            options={
                'db_table': 'daily_forms',
            },
        ),
        migrations.CreateModel(
            name='FinalFormSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Introductory'), (1, 'Novice'), (2, 'Intermidiate'), (3, 'Advanced'), (4, 'Mastered')], default=0, null=True)),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('finalform', models.ForeignKey(db_column='finalform_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='api.finalform')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'finalform_skills',
                'unique_together': {('finalform', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='finalform',
            name='skills',
            field=models.ManyToManyField(related_name='final_forms', through='api.FinalFormSkill', to='api.skill'),
        ),
        migrations.CreateModel(
            name='DailyFormSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Introductory'), (1, 'Novice'), (2, 'Intermidiate'), (3, 'Advanced'), (4, 'Mastered')], default=0, null=True)),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('dailyform', models.ForeignKey(db_column='dailyform_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='api.dailyform')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='dailyform_links', to='api.skill')),
            ],
            options={
                'db_table': 'dailyform_skills',
                'unique_together': {('dailyform', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='dailyform',
            name='skills',
            field=models.ManyToManyField(related_name='daily_forms', through='api.DailyFormSkill', to='api.skill'),
        ),
    ]
