# Generated by Django 6.0.3 on 2026-03-13 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalformskill',
            name='finalform_id',
        ),
        migrations.RemoveField(
            model_name='finalformskill',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='ridercaregiver',
            name='caregiver_id',
        ),
        migrations.RemoveField(
            model_name='ridercaregiver',
            name='rider_id',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='riders',
            field=models.ManyToManyField(to='api.rider'),
        ),
        migrations.AddField(
            model_name='dailyform',
            name='skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
        migrations.AddField(
            model_name='finalform',
            name='skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
        migrations.AlterField(
            model_name='dailyform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DailyFormSkill',
        ),
        migrations.DeleteModel(
            name='FinalFormSkill',
        ),
        migrations.DeleteModel(
            name='RiderCaregiver',
        ),
    ]
