# Generated by Django 6.0.3 on 2026-03-14 00:29

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='isemergencycontact',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='riders',
        ),
        migrations.RemoveField(
            model_name='dailyform',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='finalform',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='id',
            field=models.UUIDField(db_column='caregiver_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.UUIDField(db_column='rider_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CaregiverRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('lastname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('phone', models.TextField(blank=True, null=True, validators=[api.models.validate_phone])),
                ('email', models.TextField(blank=True, null=True, validators=[api.models.validate_email])),
                ('isemergencycontact', models.BooleanField(blank=True, null=True)),
                ('caregiver_id', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='api.caregiver')),
                ('rider_id', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
            options={
                'db_table': 'caregiver_riders',
            },
        ),
        migrations.CreateModel(
            name='DailyFormSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('dailyform_id', models.ForeignKey(db_column='dailyform_id', on_delete=django.db.models.deletion.CASCADE, to='api.dailyform')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'dailyform_skills',
                'unique_together': {('dailyform_id', 'skill_id')},
            },
        ),
        migrations.CreateModel(
            name='FinalFormSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('finalform_id', models.ForeignKey(db_column='finalform_id', on_delete=django.db.models.deletion.CASCADE, to='api.finalform')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'finalform_skills',
                'unique_together': {('finalform_id', 'skill_id')},
            },
        ),
    ]
