# Generated by Django 6.0.3 on 2026-03-14 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_caregiverrider_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverrider',
            old_name='caregiver_id',
            new_name='caregiver',
        ),
        migrations.RenameField(
            model_name='caregiverrider',
            old_name='rider_id',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='dailyform',
            old_name='rider_id',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='dailyform',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='endttime',
            new_name='endtime',
        ),
        migrations.AlterUniqueTogether(
            name='caregiverrider',
            unique_together={('caregiver', 'rider')},
        ),
        migrations.RemoveField(
            model_name='finalform',
            name='session_id',
        ),
        migrations.AddField(
            model_name='dailyform',
            name='skills',
            field=models.ManyToManyField(related_name='daily_forms', through='api.DailyFormSkill', to='api.skill'),
        ),
        migrations.AddField(
            model_name='finalform',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_forms', to='api.session'),
        ),
        migrations.AddField(
            model_name='finalform',
            name='skills',
            field=models.ManyToManyField(related_name='final_forms', through='api.FinalFormSkill', to='api.skill'),
        ),
        migrations.AddField(
            model_name='rider',
            name='caregivers',
            field=models.ManyToManyField(related_name='riders', through='api.CaregiverRider', to='api.caregiver'),
        ),
        migrations.AddField(
            model_name='skill',
            name='formlevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dailyformskill',
            name='dailyform_id',
            field=models.ForeignKey(db_column='dailyform_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='api.dailyform'),
        ),
        migrations.AlterField(
            model_name='dailyformskill',
            name='skill_id',
            field=models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='dailyform_links', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='finalform',
            name='rider_id',
            field=models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_forms', to='api.rider'),
        ),
    ]
