# Generated by Django 6.0.3 on 2026-03-13 01:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('lastname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('phone', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(15)])),
                ('email', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(254)])),
                ('isemergencycontact', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caregivers',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('lastname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('isquickstart', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessionnumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('starttime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endttime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skillname', models.TextField(validators=[django.core.validators.MaxLengthValidator(120)])),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='RiderCaregiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caregiver_id', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.caregiver')),
                ('rider_id', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.rider')),
            ],
            options={
                'db_table': 'rider_caregivers',
            },
        ),
        migrations.AddField(
            model_name='rider',
            name='session_id',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.session'),
        ),
        migrations.CreateModel(
            name='FinalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('rider_id', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.rider')),
                ('session_id', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.session')),
            ],
            options={
                'db_table': 'final_forms',
            },
        ),
        migrations.CreateModel(
            name='DailyForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('rider_id', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.rider')),
                ('session_id', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.session')),
            ],
            options={
                'db_table': 'daily_forms',
            },
        ),
        migrations.CreateModel(
            name='FinalFormSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finalform_id', models.ForeignKey(db_column='finalform_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.finalform')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.skills')),
            ],
            options={
                'db_table': 'finalform_skills',
            },
        ),
        migrations.CreateModel(
            name='DailyFormSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dailyform_id', models.ForeignKey(db_column='dailyform_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.dailyform')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.skills')),
            ],
            options={
                'db_table': 'dailyform_skills',
            },
        ),
    ]
