# Generated by Django 6.0.3 on 2026-03-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_caregiver_email_remove_caregiver_firstname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caregiverrider',
            unique_together={('caregiver_id', 'rider_id')},
        ),
    ]
