# Generated by Django 6.0.3 on 2026-03-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_caregiver_id_caregiverrider_caregiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyformskill',
            old_name='dailyform_id',
            new_name='dailyform',
        ),
        migrations.RenameField(
            model_name='dailyformskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='finalform',
            old_name='rider_id',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='finalformskill',
            old_name='finalform_id',
            new_name='finalform',
        ),
        migrations.RenameField(
            model_name='finalformskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='dailyformskill',
            unique_together={('dailyform', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='finalformskill',
            unique_together={('finalform', 'skill')},
        ),
    ]
