PHONE_MAX_LEN = 15
ZIPCODE_MAX_LEN = 15
GROUPSIZE_MAX_LEN = 15

SESSION_MIN_NUMBER = 1
SESSION_MAX_NUMBER = 5

SKILL_LEVEL_MIN = 1
SKILL_LEVEL_MAX = 5

FORM_LEVEL_MIN = 1
FORM_LEVEL_MAX = 3

EMAIL_MAX_LEN = 254
NAME_MAX_LEN = 120
SHORT_TEXT_MAX_LEN = 80
MEDIUM_TEXT_MAX_LEN = 255
LONG_TEXT_MAX_LEN = 2000
SKILL_NAME_MAX_LEN = 120
STATE_CODE_MAX_LEN = 10

# Search field limits
SEARCH_MAX_LEN = 255